<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ContactIcon.jpg" />
    <None Remove="newcontact.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="30.0.1" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ContactIcon.jpg" />
    <Resource Include="newcontact.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\en_US.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>en_US.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\en_US.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>en_US.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
